apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki
  ports:
  - protocol: TCP
    port: 3100
    targetPort: 3100
  - protocol: TCP
    port: 9095
    targetPort: 9095
  type: LoadBalancer