version: '3.8'

services:
  nginx:
    image: josovd2/pet:latest
    restart: unless-stopped
    ports:
      - "80:80"

  prometheus:
    image: prom/prometheus:v2.39.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.4.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards/kubernetes_dashboard.json:/var/lib/grafana/dashboards/kubernetes_dashboard.json
      - ./grafana/provisioning/dashboards/loki_dash.json:/var/lib/grafana/dashboards/loki_dash.json
      - ./grafana/config/grafana_loki.ini:/etc/grafana/grafana_loki.ini
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - loki
      - prometheus
    hostname: grafana
    environment:
      - GF_PROVISIONING_ENABLED=true
      - GF_PROVISIONING_DASHBOARDS_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_DASHBOARDS_JSON_PATH=/etc/grafana/provisioning/dashboards
      - GF_DASHBOARDS_JSON_ENABLED=true
    restart: unless-stopped

  loki:
    image: grafana/loki:2.7.0
    ports:
      - "3100:3100"
      - "9095:9095"
    volumes:
      - ./local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    hostname: loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.7.0
    ports:
      - "9080:9080"
    volumes:
      - ./promtail.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
      - /tmp:/tmp
    command: -config.file=/etc/promtail/config.yaml
    hostname: promtail
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    devices:
      - /dev/kmsg:/dev/kmsg

volumes:
  grafana_datasources:
  grafana_dashboards:
  grafana_data:
