apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: default
data:
  datasource.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://172.18.0.1:9090
        isDefault: true
        version: 1
        editable: true

      - name: Loki
        type: loki
        access: proxy
        url: http://172.18.0.1:3100
        version: 1
        editable: true