apiVersion: 1

datasources:
  - name: MyDataSource
    type: prometheus
    access: proxy
    url: http://172.18.0.1:9090
    jsonData:
      timeInterval: "5s"
    basicAuth: false

  - name: Loki
    type: loki
    access: proxy
    url: http://172.18.0.1:3100
    jsonData:
      maxLines: 1000
    isDefault: true
