apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  config.yaml: |
    server:
      http_listen_port: 9080

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://172.18.0.1:3100/loki/api/v1/push

    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - 172.18.0.1
            labels:
              job: varlogs
              instance: 172.18.0.1
              __path__: /var/log/*.log