name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        run: |
          echo "" | docker login -u "" --password-stdin
          docker-compose build
          docker-compose push

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: 
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key user@your-server "cd /home/josov/my_project && git pull && docker-compose up -d"
